spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  datasource:
    url: jdbc:postgresql://localhost:5432/octo-waffle
    driverClassName: org.postgresql.Driver
    username: postgres
    password: 8263

  jpa:
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        show-sql: true
        format_sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
